import { hasPhrase } from "../utils/helpers.ts";
import type { NewsTopic } from "../types.ts";

export function extractQuery(tokens: string[], ignore: string[]) {
    return tokens.filter((t) => !ignore.includes(t)).join(" ");
}

export function extractNewsScope(tokens: string[]): "local" | "international" | null {
    if (tokens.includes("local") || tokens.includes("nearby") || hasPhrase(tokens, ["in", "my", "country"])) return "local";
    if (tokens.includes("international") || tokens.includes("global") || tokens.includes("world")) return "international";
    return null;
}

export function extractNewsTopic(tokens: string[]): NewsTopic | null {
    const topicMap: Record<string, NewsTopic> = {
        tech: { code: "TECHNOLOGY", label: "tech" },
        technology: { code: "TECHNOLOGY", label: "tech" },
        ai: { code: "TECHNOLOGY", label: "AI" },
        artificial: { code: "TECHNOLOGY", label: "AI" },
        intelligence: { code: "TECHNOLOGY", label: "AI" },
        safety: { code: "TECHNOLOGY", label: "AI safety" },
        aisafety: { code: "TECHNOLOGY", label: "AI safety" },
        ethics: { code: "TECHNOLOGY", label: "AI ethics" },
        alignment: { code: "TECHNOLOGY", label: "AI alignment" },
        ml: { code: "TECHNOLOGY", label: "machine learning" },
        machine: { code: "TECHNOLOGY", label: "machine learning" },
        learning: { code: "TECHNOLOGY", label: "machine learning" },
        llm: { code: "TECHNOLOGY", label: "LLMs" },
        llms: { code: "TECHNOLOGY", label: "LLMs" },
        chatbot: { code: "TECHNOLOGY", label: "chatbots" },
        chatbots: { code: "TECHNOLOGY", label: "chatbots" },
        robotics: { code: "TECHNOLOGY", label: "robotics" },
        robot: { code: "TECHNOLOGY", label: "robotics" },
        drones: { code: "TECHNOLOGY", label: "drones" },
        gadgets: { code: "TECHNOLOGY", label: "gadgets" },
        hardware: { code: "TECHNOLOGY", label: "hardware" },
        software: { code: "TECHNOLOGY", label: "software" },
        apps: { code: "TECHNOLOGY", label: "apps" },
        app: { code: "TECHNOLOGY", label: "apps" },
        mobile: { code: "TECHNOLOGY", label: "mobile" },
        android: { code: "TECHNOLOGY", label: "android" },
        ios: { code: "TECHNOLOGY", label: "iOS" },
        apple: { code: "TECHNOLOGY", label: "Apple" },
        google: { code: "TECHNOLOGY", label: "Google" },
        microsoft: { code: "TECHNOLOGY", label: "Microsoft" },
        meta: { code: "TECHNOLOGY", label: "Meta" },
        amazon: { code: "TECHNOLOGY", label: "Amazon" },
        cybersecurity: { code: "TECHNOLOGY", label: "cybersecurity" },
        security: { code: "TECHNOLOGY", label: "security" },
        hacking: { code: "TECHNOLOGY", label: "hacking" },
        privacy: { code: "TECHNOLOGY", label: "privacy" },
        data: { code: "TECHNOLOGY", label: "data" },
        database: { code: "TECHNOLOGY", label: "databases" },
        databases: { code: "TECHNOLOGY", label: "databases" },
        cloud: { code: "TECHNOLOGY", label: "cloud" },
        aws: { code: "TECHNOLOGY", label: "AWS" },
        azure: { code: "TECHNOLOGY", label: "Azure" },
        gcp: { code: "TECHNOLOGY", label: "GCP" },
        devops: { code: "TECHNOLOGY", label: "DevOps" },
        programming: { code: "TECHNOLOGY", label: "programming" },
        coding: { code: "TECHNOLOGY", label: "coding" },
        openai: { code: "TECHNOLOGY", label: "OpenAI" },
        blockchain: { code: "BUSINESS", label: "blockchain" },
        defi: { code: "BUSINESS", label: "DeFi" },
        nft: { code: "BUSINESS", label: "NFTs" },
        nfts: { code: "BUSINESS", label: "NFTs" },
        token: { code: "BUSINESS", label: "tokens" },
        tokens: { code: "BUSINESS", label: "tokens" },
        stablecoin: { code: "BUSINESS", label: "stablecoins" },
        stablecoins: { code: "BUSINESS", label: "stablecoins" },
        regulation: { code: "BUSINESS", label: "regulation" },
        regulatory: { code: "BUSINESS", label: "regulation" },
        tariffs: { code: "BUSINESS", label: "tariffs" },
        inflation: { code: "BUSINESS", label: "inflation" },
        recession: { code: "BUSINESS", label: "recession" },
        gdp: { code: "BUSINESS", label: "GDP" },
        earnings: { code: "BUSINESS", label: "earnings" },
        ipo: { code: "BUSINESS", label: "IPOs" },
        ipos: { code: "BUSINESS", label: "IPOs" },
        mergers: { code: "BUSINESS", label: "M&A" },
        acquisitions: { code: "BUSINESS", label: "M&A" },
        mna: { code: "BUSINESS", label: "M&A" },
        funding: { code: "BUSINESS", label: "funding" },
        fundraising: { code: "BUSINESS", label: "funding" },
        layoffs: { code: "BUSINESS", label: "layoffs" },
        salaries: { code: "BUSINESS", label: "salaries" },
        wage: { code: "BUSINESS", label: "wages" },
        wages: { code: "BUSINESS", label: "wages" },
        commodities: { code: "BUSINESS", label: "commodities" },
        oil: { code: "BUSINESS", label: "oil" },
        gas: { code: "BUSINESS", label: "energy" },
        energy: { code: "BUSINESS", label: "energy" },
        climatechange: { code: "SCIENCE", label: "climate" },
        wildfires: { code: "SCIENCE", label: "wildfires" },
        hurricanes: { code: "SCIENCE", label: "hurricanes" },
        earthquakes: { code: "SCIENCE", label: "earthquakes" },
        disasters: { code: "SCIENCE", label: "disasters" },
        pandemic: { code: "HEALTH", label: "pandemic" },
        vaccines: { code: "HEALTH", label: "vaccines" },
        mental: { code: "HEALTH", label: "mental health" },
        mindfulness: { code: "HEALTH", label: "mindfulness" },
        diet: { code: "HEALTH", label: "nutrition" },
        diabetes: { code: "HEALTH", label: "diabetes" },
        cancer: { code: "HEALTH", label: "cancer" },
        covid: { code: "HEALTH", label: "COVID" },
        biotech: { code: "HEALTH", label: "biotech" },
        pharma: { code: "HEALTH", label: "pharma" },
        drugs: { code: "HEALTH", label: "drugs" },
        hospitals: { code: "HEALTH", label: "hospitals" },
        insurance: { code: "HEALTH", label: "insurance" },
        schools: { code: "NATION", label: "education" },
        universities: { code: "NATION", label: "education" },
        tuition: { code: "NATION", label: "education" },
        renters: { code: "BUSINESS", label: "housing" },
        mortgages: { code: "BUSINESS", label: "housing" },
        startupsfunding: { code: "BUSINESS", label: "startups funding" },
        venturecapital: { code: "BUSINESS", label: "venture capital" },
        seed: { code: "BUSINESS", label: "startups funding" },
        seriesa: { code: "BUSINESS", label: "startups funding" },
        seriesb: { code: "BUSINESS", label: "startups funding" },
        seriesc: { code: "BUSINESS", label: "startups funding" },
        founders: { code: "BUSINESS", label: "startups" },
        entrepreneurship: { code: "BUSINESS", label: "startups" },
        creator: { code: "ENTERTAINMENT", label: "creator economy" },
        creators: { code: "ENTERTAINMENT", label: "creator economy" },
        youtube: { code: "ENTERTAINMENT", label: "YouTube" },
        tiktok: { code: "ENTERTAINMENT", label: "TikTok" },
        instagram: { code: "ENTERTAINMENT", label: "Instagram" },
        twitch: { code: "ENTERTAINMENT", label: "Twitch" },
        podcasts: { code: "ENTERTAINMENT", label: "podcasts" },
        books: { code: "ENTERTAINMENT", label: "books" },
        awards: { code: "ENTERTAINMENT", label: "awards" },
        fashion: { code: "ENTERTAINMENT", label: "fashion" },
        art: { code: "ENTERTAINMENT", label: "art" },
        theater: { code: "ENTERTAINMENT", label: "theater" },
        broadway: { code: "ENTERTAINMENT", label: "theater" },
        photography: { code: "ENTERTAINMENT", label: "photography" },
        design: { code: "ENTERTAINMENT", label: "design" },
        festival: { code: "ENTERTAINMENT", label: "festivals" },
        concerts: { code: "ENTERTAINMENT", label: "concerts" },
        comedy: { code: "ENTERTAINMENT", label: "comedy" },
        pc: { code: "ENTERTAINMENT", label: "PC gaming" },
        console: { code: "ENTERTAINMENT", label: "console gaming" },
        playstation: { code: "ENTERTAINMENT", label: "PlayStation" },
        xbox: { code: "ENTERTAINMENT", label: "Xbox" },
        nintendo: { code: "ENTERTAINMENT", label: "Nintendo" },
        worldcup: { code: "SPORTS", label: "World Cup" },
        olympics: { code: "SPORTS", label: "Olympics" },
        cricket: { code: "SPORTS", label: "cricket" },
        rugby: { code: "SPORTS", label: "rugby" },
        boxing: { code: "SPORTS", label: "boxing" },
        mma: { code: "SPORTS", label: "MMA" },
        ufc: { code: "SPORTS", label: "UFC" },
        wwe: { code: "SPORTS", label: "WWE" },
        wnba: { code: "SPORTS", label: "WNBA" },
        womens: { code: "SPORTS", label: "women's sports" },
        baseball: { code: "SPORTS", label: "baseball" },
        basketball: { code: "SPORTS", label: "basketball" },
        congress: { code: "NATION", label: "politics" },
        senate: { code: "NATION", label: "politics" },
        courts: { code: "NATION", label: "law" },
        supreme: { code: "NATION", label: "law" },
        diplomacy: { code: "WORLD", label: "diplomacy" },
        sanctions: { code: "WORLD", label: "sanctions" },
        refugees: { code: "WORLD", label: "refugees" },
        border: { code: "WORLD", label: "immigration" },
        defense: { code: "WORLD", label: "defense" },
        military: { code: "WORLD", label: "military" },
        humanitarian: { code: "WORLD", label: "humanitarian" },
        aid: { code: "WORLD", label: "aid" },
        africa: { code: "WORLD", label: "Africa" },
        europe: { code: "WORLD", label: "Europe" },
        asia: { code: "WORLD", label: "Asia" },
        middleeast: { code: "WORLD", label: "Middle East" },
        latinamerica: { code: "WORLD", label: "Latin America" },
        uk: { code: "WORLD", label: "UK" },
        usa: { code: "WORLD", label: "USA" },
        canada: { code: "WORLD", label: "Canada" },
        india: { code: "WORLD", label: "India" },
        china: { code: "WORLD", label: "China" },
        russia: { code: "WORLD", label: "Russia" },
        ukraine: { code: "WORLD", label: "Ukraine" },
        israel: { code: "WORLD", label: "Israel" },
        palestine: { code: "WORLD", label: "Palestine" },
        gaza: { code: "WORLD", label: "Gaza" },
        crypto: { code: "BUSINESS", label: "crypto" },
        cryptocurrency: { code: "BUSINESS", label: "crypto" },
        bitcoin: { code: "BUSINESS", label: "crypto" },
        ethereum: { code: "BUSINESS", label: "crypto" },
        web3: { code: "TECHNOLOGY", label: "web3" },
        startups: { code: "BUSINESS", label: "startups" },
        startup: { code: "BUSINESS", label: "startups" },
        venture: { code: "BUSINESS", label: "venture" },
        vc: { code: "BUSINESS", label: "venture" },
        economy: { code: "BUSINESS", label: "economy" },
        markets: { code: "BUSINESS", label: "markets" },
        stocks: { code: "BUSINESS", label: "stocks" },
        investing: { code: "BUSINESS", label: "investing" },
        finance: { code: "BUSINESS", label: "finance" },
        fintech: { code: "BUSINESS", label: "fintech" },
        banking: { code: "BUSINESS", label: "banking" },
        realestate: { code: "BUSINESS", label: "real estate" },
        housing: { code: "BUSINESS", label: "housing" },
        jobs: { code: "BUSINESS", label: "jobs" },
        labor: { code: "BUSINESS", label: "labor" },
        business: { code: "BUSINESS", label: "business" },
        sports: { code: "SPORTS", label: "sports" },
        sport: { code: "SPORTS", label: "sports" },
        nba: { code: "SPORTS", label: "NBA" },
        nfl: { code: "SPORTS", label: "NFL" },
        mlb: { code: "SPORTS", label: "MLB" },
        nhl: { code: "SPORTS", label: "NHL" },
        soccer: { code: "SPORTS", label: "soccer" },
        football: { code: "SPORTS", label: "football" },
        tennis: { code: "SPORTS", label: "tennis" },
        golf: { code: "SPORTS", label: "golf" },
        f1: { code: "SPORTS", label: "Formula 1" },
        racing: { code: "SPORTS", label: "racing" },
        esports: { code: "SPORTS", label: "esports" },
        gaming: { code: "ENTERTAINMENT", label: "gaming" },
        entertainment: { code: "ENTERTAINMENT", label: "entertainment" },
        movies: { code: "ENTERTAINMENT", label: "movies" },
        tv: { code: "ENTERTAINMENT", label: "TV" },
        streaming: { code: "ENTERTAINMENT", label: "streaming" },
        music: { code: "ENTERTAINMENT", label: "music" },
        celebrities: { code: "ENTERTAINMENT", label: "celebrities" },
        culture: { code: "ENTERTAINMENT", label: "culture" },
        science: { code: "SCIENCE", label: "science" },
        space: { code: "SCIENCE", label: "space" },
        nasa: { code: "SCIENCE", label: "space" },
        climate: { code: "SCIENCE", label: "climate" },
        environment: { code: "SCIENCE", label: "environment" },
        health: { code: "HEALTH", label: "health" },
        healthcare: { code: "HEALTH", label: "health" },
        medicine: { code: "HEALTH", label: "medicine" },
        wellness: { code: "HEALTH", label: "wellness" },
        fitness: { code: "HEALTH", label: "fitness" },
        nutrition: { code: "HEALTH", label: "nutrition" },
        travel: { code: "WORLD", label: "travel" },
        world: { code: "WORLD", label: "world" },
        global: { code: "WORLD", label: "world" },
        geopolitics: { code: "WORLD", label: "geopolitics" },
        war: { code: "WORLD", label: "world" },
        politics: { code: "NATION", label: "politics" },
        government: { code: "NATION", label: "politics" },
        elections: { code: "NATION", label: "elections" },
        policy: { code: "NATION", label: "policy" },
        law: { code: "NATION", label: "law" },
        crime: { code: "NATION", label: "crime" },
        education: { code: "NATION", label: "education" },
        immigration: { code: "NATION", label: "immigration" },
        national: { code: "NATION", label: "national" },
    };

    // Handle multi-word topics first (bigrams)
    for (let i = 0; i < tokens.length - 1; i++) {
        const pair = `${tokens[i]} ${tokens[i + 1]}`;
        if (pair === "ai safety") return { code: "TECHNOLOGY", label: "AI safety" };
        if (pair === "startup funding") return { code: "BUSINESS", label: "startups funding" };
        if (pair === "venture capital") return { code: "BUSINESS", label: "venture capital" };
        if (pair === "machine learning") return { code: "TECHNOLOGY", label: "machine learning" };
        if (pair === "artificial intelligence") return { code: "TECHNOLOGY", label: "AI" };
        if (pair === "real estate") return { code: "BUSINESS", label: "real estate" };
        if (pair === "electric vehicles") return { code: "SCIENCE", label: "electric vehicles" };
        if (pair === "mental health") return { code: "HEALTH", label: "mental health" };
        if (pair === "data privacy") return { code: "TECHNOLOGY", label: "privacy" };
    }

    for (const t of tokens) {
        if (topicMap[t]) return topicMap[t];
    }
    return null;
}

export function extractNewsIndex(tokens: string[]) {
    const numberMap: Record<string, number> = {
        "one": 0, "first": 0, "1": 0,
        "two": 1, "second": 1, "2": 1,
        "three": 2, "third": 2, "3": 2,
        "four": 3, "fourth": 3, "4": 3,
        "five": 4, "fifth": 4, "5": 4,
        "six": 5, "sixth": 5, "6": 5,
    };
    const token = tokens.find((t) => numberMap[t] !== undefined);
    return token ? numberMap[token] : null;
}
